# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebc1e587ac8755f09f3f8057d6af95ba0b8b38afd65cf2bd089dc5c42af314a7f04249ff5e54756970087e1fb7e9d6667cf636c296e766ae7c0c0cc2212cfa69

test:
  secret_key_base: 6395652de6a551bc9969efe0154a02185be2b05f270925d911ba2496e3fc3b3eae73eb1173259b876edda95e826685ad2b1cb41447d35a545084bd157bb6d91f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
